services:
  nginx-service:
    image: nginx:alpine
    container_name: nginx_web_service
    # restart: always

    ports:
      - "80:80"
      - "443:443"
    
    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    
    

# docker compose -f <file-name> up -docker
# docker compose -f <file-name> down 

# docker exec nginx_web_service nginx -s start
# docker exec nginx_web_service nginx -s reload
# docker exec nginx_web_service nginx -s down

