CREATE USER debezium
WITH PASSWORD 'debezium'
REPLICATION;

GRANT CONNECT ON DATABASE appdb TO debezium;
GRANT CREATE ON DATABASE appdb TO debezium;

\connect appdb;

GRANT USAGE ON SCHEMA public TO debezium;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO debezium;

GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO debezium;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO debezium;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON SEQUENCES TO debezium;